import Config

defmodule Credentials do
  @doc """
  fetch password from ~/.pgpass for a given username
  """
  def fetch_pass_from_pgpass(username) do
    filename = Path.join(System.get_env("HOME"), ".pgpass")

    filename
    |> File.read!()
    |> String.split("\n")
    |> Enum.find_value(nil, fn line ->
      case line do
        "#" <> _rest -> # comment
            nil
        line ->
          case String.split(line, ":") do
            [_,_,_, ^username, password] -> password # Return password if matched
            _ -> nil
          end
      end
    end)
  end
end

# Configure your database
config :toy_app, ToyApp.Repo,
  username: "dbuser",
  password: Credentials.fetch_pass_from_pgpass("dbuser"),
  database: "toy_app_dev",
  hostname: "localhost",
  show_sensitive_data_on_connection_error: true,
  pool_size: 10

# For development, we disable any cache and enable
# debugging and code reloading.
#
# The watchers configuration can be used to run external
# watchers to your application. For example, we use it
# with esbuild to bundle .js and .css sources.
config :toy_app, ToyAppWeb.Endpoint,
  # Binding to loopback ipv4 address prevents access from other machines.
  # Change to `ip: {0, 0, 0, 0}` to allow access from other machines.
  http: [ip: {127, 0, 0, 1}, port: 4000],
  check_origin: false,
  code_reloader: true,
  debug_errors: true,
  secret_key_base: "0Lq2xkyilKuRpjQpRaCIwf8T0v8oPMMfU7geSX4a4JierMTXUXiZSba83wVWknKP",
  watchers: [
    # Start the esbuild watcher by calling Esbuild.install_and_run(:default, args)
    esbuild: {Esbuild, :install_and_run, [:default, ~w(--sourcemap=inline --watch)]}
  ]

# ## SSL Support
#
# In order to use HTTPS in development, a self-signed
# certificate can be generated by running the following
# Mix task:
#
#     mix phx.gen.cert
#
# Note that this task requires Erlang/OTP 20 or later.
# Run `mix help phx.gen.cert` for more information.
#
# The `http:` config above can be replaced with:
#
#     https: [
#       port: 4001,
#       cipher_suite: :strong,
#       keyfile: "priv/cert/selfsigned_key.pem",
#       certfile: "priv/cert/selfsigned.pem"
#     ],
#
# If desired, both `http:` and `https:` keys can be
# configured to run both http and https servers on
# different ports.

# Watch static and templates for browser reloading.
config :toy_app, ToyAppWeb.Endpoint,
  live_reload: [
    patterns: [
      ~r"priv/static/.*(js|css|png|jpeg|jpg|gif|svg)$",
      ~r"priv/gettext/.*(po)$",
      ~r"lib/toy_app_web/(live|views)/.*(ex)$",
      ~r"lib/toy_app_web/templates/.*(eex)$"
    ]
  ]

# Do not include metadata nor timestamps in development logs
config :logger, :console, format: "[$level] $message\n"

# Set a higher stacktrace during development. Avoid configuring such
# in production as building large stacktraces may be expensive.
config :phoenix, :stacktrace_depth, 20

# Initialize plugs at runtime for faster development compilation
config :phoenix, :plug_init_mode, :runtime
